### ISSUE TITLE
Password Login Error

### ISSUE THREAD

**Issue by user2255** [Shade-/MyFacebook-Connect#35]
Trying to understand the difference between login and register. There is no link for register. When trying to register with choose password settings in the admin area of "One-click registration" I get the error code: The password you entered is not complex enough. Please enter a password that is at least 6 characters long, and contains an upper case letter, lower case letter and a number., but there is no field to choose password.

**Comment by Shade-** [comment]
Fixed in 6746f65464b7fb4e894888f29140221a0e6e89bc.
