### ISSUE TITLE
Facebook connect problem

### ISSUE THREAD

**Issue by Boia11** [Shade-/MyFacebook-Connect#36]
I have follow the istruction but when i try to get link to FB:
- the system open FB for acceptation of link with app

![screenshot 2014-12-02 15 36 40](https://cloud.githubusercontent.com/assets/10048197/5264270/b4902a06-7a39-11e4-8a67-0662f39b1fa2.png)

- when come back to MyBB the system screen this error:
"An unknown error occurred. The output of the error is:
An active access token must be used to query information about the current user.
Please report this error to an administrator and try again."

![screenshot 2014-12-02 15 36 57](https://cloud.githubusercontent.com/assets/10048197/5264284/cb8e5e4e-7a39-11e4-98fe-6541c1b07e6e.png)

But after more test, I haven't found the problem.

**Comment by rehman259** [comment]
Dear Shade,

I am using MyfacebookConnect (2.2) plugin on MyBB forum(1.6.12). I have just converted my site to SSL, after that my Facebook login is not working.

The request go to facebook and ask for username and password for user and it redirect to my site with the error "An active access token must be used to query information about the current user." 

i have tried the solution you have provided above but issue is not resolved yet.

so please let me know what will be the solution, I will be grateful for your help.

this is the forum
https://www.propertytribes.com/

**Comment by Shade-** [comment]
Version 2.2 is deprecated, as its SDK is not supported by Facebook anymore. The latest version available is 3.1 which includes the newest SDK.

**Comment by rehman259** [comment]
Thank you for your response Shade.

Actually the FB login was working fine without SSL but it is not working once we converted to SSL. 
So is there any short fix I can apply to resolved the issue or Do I need to update the plugin?
There is a lot of customization is done by developers in current plugin, so if I update then previous code will be gone.

What you think is the best solution in which we can fix as soon as possible?

I look forward to hear from you soon.

**Comment by Shade-** [comment]
Unfortunately I don't support older versions anymore, sorry. If you decide to customize the stock version, you also need to supply eventual bugs by yourself. Also, it's probably best to ask for new features to me rather than customize my plugins. I'm always open to requests.

**Comment by rehman259** [comment]
OK fine. I am using MyBB forum veriosn 1.6. Is MyfacebookConnect 3.1 supported by MyBB 1.6??

**Comment by Shade-** [comment]
Yes, as long as you add the global_intermediate hook. Read [the installation instructions](https://www.mybboost.com/thread-how-to-install).

From 3.0 onwards there are some major changes to the minimum requirements. Make sure your host is compliant with them. Also, don't forget to save full dumps of both your database and your files.

To update, read the [release instructions](https://www.mybboost.com/thread-release-myfacebook-connect-3-1?pid=681#pid681).

**Comment by Shade-** [comment]
Nonetheless, I would recommend you to update your MyBB version to the latest available (1.8.11) in order to be secured against malicious attacks. If you feel like your board is too customized to make the big leap from 1.6 to 1.8, update your board to the latest 1.6 version at least.

**Comment by rehman259** [comment]
I am using MyBB 1.6 but there is a lot of customization in forum.  FB login was working fine but it suddenly not working since two days.

I want to use your FB plugin 3.0. There are some customization in my current FB plugin, Do I need to sync those changes to new Plugin.

How to update the plugin to 3.0? 

I look forward to hear from you soon.

**Comment by Shade-** [comment]
I have listed all the necessary references above.
