### ISSUE TITLE
An unknown error occurred. The output of the error is: An active access token must be used to query information about the current user.

### ISSUE THREAD

**Issue by syabilmahadzir89** [Shade-/MyFacebook-Connect#44]
Anybody here can help me ? 

My Forums Link : https://www.giler-it.com/

**Comment by Shade-** [comment]
This is usually caused by your server which does not have port 443 opened (you need to open it if this is the case).

**Comment by Shade-** [comment]
Could you try the latest update I've submitted? Version 2.2 includes a handy port check fired upon installation and an update to the latest Facebook SDK.

**Comment by Shade-** [comment]
Feel free to reopen if you encounter this issue with the latest version.
