### ISSUE TITLE
member_do_register_end plugin cannot access $user_info

### ISSUE THREAD

**Issue by moz1966** [Shade-/MyFacebook-Connect#46]
In class_facebook.php, line 277 you have

> $user_info = $userhandler->insert_user();
> 
>  $plugins->run_hooks("member_do_register_end");

But inside plugins run from that hook, they cannot access the info in $user_info.  For the normal registration process, the $user_info variable is populated with the new user info for the plugins.

**Comment by Shade-** [comment]
Darn you are right. That hook is useless. It has to be edited with a pass-by-reference hook, although the default one doesn't come like that. A fresh new hook might be necessary. Moving to 2.4.

**Comment by Shade-** [comment]
Removed in 6746f65464b7fb4e894888f29140221a0e6e89bc.
