### ISSUE TITLE
your server's 443 port seems to be closed

### ISSUE THREAD

**Issue by rmalenko** [Shade-/MyFacebook-Connect#47]
Hello,

Could you help me, please? I cannot activate this plugin because get message 443 port closed.
However, I can connect to Facebook by HTTPS.

This is lynx from console
https://dl.dropboxusercontent.com/u/16852973/Selection_003.png

**Comment by Shade-** [comment]
The check is done using PHP cURL which is the one used by the SDK, maybe it's the cURL configuration not being set up properly. You might delete the lines in the code that perform the check and install it if you want to give it a try. The lines are included in the myfbconnect_install() function and are quite recognizeable (just an if conditional statement).

**Comment by rmalenko** [comment]
Thank you for answer.
Curl http://getleanforums.com/123.php
I have commented this code and get blank page now.
Might my problem called because I use MyBB 1.8?

`
/**
function verify_port_443()
{
	global $lang;
	
	// 3 seconds timeout to check for port 443 is enough
	$fp = @fsockopen('172.31.42.117', 443, $errno, $errstr, 3);
	
	// Port 443 is closed or blocked
	if (!$fp) {
	
		flash_message($lang->myfbconnect_error_port_443_not_open, 'error');
		admin_redirect("index.php?module=config-plugins");
	    
	}
	
	return false;

}
*/
`

**Comment by Shade-** [comment]
You must not blank out the function itself, because the function is called within the myfbconnect_install() function (and if it does not exists, the installation will output a blank page in the browser and will abort itself).

You must wipe out the function call.

**Comment by rmalenko** [comment]
Thank you. I have changed if (!$fp) to if ($fp). I am not a developer :)
