### ISSUE TITLE
Login link does not work with Force Users to Login option enabled

### ISSUE THREAD

**Issue by marcandrews** [Shade-/MyFacebook-Connect#49]
When the **Force Users to Login** option is enabled the, ```myfbconnect.php?action=login``` login link does not work.

**Comment by Shade-** [comment]
There is not such option you mentioned. Are you talking about the One-click registration option instead? As far as I know, version 2.3 is running fine with that option enabled.

**Comment by lf-schmidt** [comment]
Hi, he means the MyBB general setting in the ACP (Board Settings/Login and Registration Options/Force Users to Login).

**Comment by Shade-** [comment]
Unfortunately, MyBB does not come with an easy access to the array which includes allowed pages when that option is active. It can be done with core editing, but I don't feel it necessary to add it to MFC's core version.

You can still adjust your own MyBB copy by editing global.php, line 958, add to the $force_bypass array the required patterns. It should look like this:
```php
$force_bypass = array(
	'member.php' => array(
		'login',
		'do_login',
		'logout',
		'register',
		'do_register',
		'lostpw',
		'do_lostpw',
		'activate',
		'resendactivation',
		'do_resendactivation',
		'resetpassword',
	),
	'captcha.php',
	'myfbconnect.php' => array(
		'login',
		'do_login',
		'register'
	)
);
```
