### ISSUE TITLE
Better template handling

### ISSUE THREAD

**Issue by marcandrews** [Shade-/MyFacebook-Connect#50]
After the plugin is installed and enabled, it adds `&mdash; <a href="{$mybb->settings['bburl']}/myfbconnect.php?action=login">{$lang->myfbconnect_login}</a>` to the _header_welcomeblock_guest_ template.

However, when the plugin is disabled with the master switch, these template edits still exists. The button is still there, but since `{$lang->myfbconnect_login}` is empty, it does not show.

Instead, can you a separate template bit containing the button so that when the plugin is disabled, the button is removed completely?

**Comment by Shade-** [comment]
Added `myfbconnect_login_button` you can reference with `{$facebook_login}` in 6746f65464b7fb4e894888f29140221a0e6e89bc.
