### ISSUE TITLE
Login button missing from the error_nopermission template

### ISSUE THREAD

**Issue by marcandrews** [Shade-/MyFacebook-Connect#51]
This is an extension to https://github.com/Shade-/MyFacebook-Connect/issues/50 ...

After adding a separate template bit for the login button, can you also add the button to the _error_nopermission_ template.

**Comment by Shade-** [comment]
Added in 6746f65464b7fb4e894888f29140221a0e6e89bc, although not by default. You can add `{$facebook_login}` wherever you like to reference `myfbconnect_login_button`.
