### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by satdav** [Shade-/MyFacebook-Connect#52]
Hello were is the docs for setting up this also for the twitter and the google one ps I am getting 

Given URL is not permitted by the Application configuration: One or more of the given URLs is not permitted by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

I am using url http://evo-nuts.co.uk

**Comment by satdav** [comment]
Invalid Scopes: publish_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

THats the error I am getting now

**Comment by Shade-** [comment]
You are using an outdated version. 2.3 includes the new scope ```publish_actions``` which replaces the old ```publish_stream```, not supported anymore.
