### ISSUE TITLE
Post on user's wall

### ISSUE THREAD

**Issue by Cu8eR** [Shade-/MyFacebook-Connect#53]
Post on user's wall
Enable this option to post a message on the user's wall when he registers or links his account to your board. Posting permissions will be automatically asked when authorizing your application. When this is active, users might wait a bit more when registering for the first time due to data being transferred to Facebook.

It is not working

**Comment by Shade-** [comment]
I will investigate. Posting to user's wall is a feature that changes over time – Facebook's APIs are changed about every 6 months, so extra features might break when a new version comes out. I don't have much spare time in this period, it's likely that I'll check in early March when I will be out of my uni exams.

**Comment by Shade-** [comment]
Discarded in 6746f65464b7fb4e894888f29140221a0e6e89bc since Facebook policy does not add prefilled posts anymore.
