### ISSUE TITLE
Unable to login via facebook bug at myfbconnect/src/base_facebook.php

### ISSUE THREAD

**Issue by arshkapoor** [Shade-/MyFacebook-Connect#57]
At admin panel bug report i am getting the following. 
myfbconnect/src/base_facebook.php   1294

Even I am also getting the following while I am trying to login in with facebook. this error shown when I am redirected back to the forum after providing facebook 

An error occurred trying to accomplish your request. A bug report has been generated and it's available in the administration panel. If you are not an administrator, contact one as soon as possible and tell him you have landed on this page. You may also try logging in with Facebook once again and see if it was just a temporary error. Sorry for the inconvenience.

WEBSITE : http://sarkarinaukriforum.org

**Comment by ErikThiart** [comment]
Is this plugin still being developed?

**Comment by Shade-** [comment]
It is, it's just I am way too busy to get into it. Sorry. As for the issue, download the report automatically generated into your ACP and post it here.

**Comment by ErikThiart** [comment]
This is wonderful, @Shade- does both the Google one and the facebook one work with MyBB 1.8?

Also would the current version work "forever" ?

I love this and would like to implement it, but just a bit concerned what would happen if this plug in stops working.

**Comment by Shade-** [comment]
All those plugins are developed specifically for MyBB 1.8 and 1.6, and they have been proven to work well in the correct environments for years. There are some bugs but they are not top priority so I won't spend time fixing them anytime soon, not until I finish with my exams.

If Facebook will stop supporting the SDK provided into the plugin, it will stop working and a new version will be developed.

**Comment by ErikThiart** [comment]
Amazing dude! Thank you..i will install the Google one. On a side note how complex are the bugs, maybe I can give you a hand with getting it done.

**Comment by Shade-** [comment]
Version 3.0 is out (6746f65464b7fb4e894888f29140221a0e6e89bc) and should fix this issue once for all.
