### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by adizam** [Shade-/MyFacebook-Connect#58]
Are you available if I have a question?

**Comment by Shade-** [comment]
Of course.

**Comment by adizam** [comment]
Would you be open to releasing the GitHub org "myalerts" ? The company I work for (https://github.com/trackif / https://business.myalerts.com) rebranded to MyAlerts earlier this year. I really want to extend this brand to GH as we start to open source more pieces of our platform.

I've been following your org throughout this year and haven't seen much usage so I figured it was appropriate to ask. GH has a conduit to request the release of inactive ORGs but I felt like reaching out to you directly. 

It would mean a lot to my fellow developers. We're working on promoting a more dev centric culture and rallying behind the brand name. The alternative is picking something like "myalerts_eng" or something generic.. but it doesn't have the same ring to it.

Let me know. Thank you !

**Comment by Shade-** [comment]
I'm absolutely not against it, however MyAlerts is a product of @euantorano so you may ask him about giving it to you.
