### ISSUE TITLE
Option to use the Facebook API without requesting for scopes

### ISSUE THREAD

**Issue by Swardu** [Shade-/MyFacebook-Connect#64]
I don't really need these scopes, but it still asks even though I disabled them.
![image](https://user-images.githubusercontent.com/27481108/41512880-48c01ba6-7292-11e8-8356-49167de3f93e.png)

**Comment by Swardu** [comment]
That was quick, thanks!

**Comment by Shade-** [comment]
Note that the functionality is untested. I do not have a test board set up currently, so I have only checked if the setting is added and if it's updating correctly. Please report any issue you might find in production.
