### ISSUE TITLE
Error message: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

### ISSUE THREAD

**Issue by Swardu** [Shade-/MyFacebook-Connect#65]
I am getting the following messge:

> Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

I am not sure what's causing it. Here's how my Redirect URI list looks like:
![image](https://user-images.githubusercontent.com/27481108/42136092-cf878c82-7d55-11e8-9127-5f3aba652ed1.png)

Here is the error log I receive:
![image](https://user-images.githubusercontent.com/27481108/42136123-3aa8b068-7d56-11e8-87e3-9253b3522eae.png)

Can't tell if it's just me, but any help is appreciated!

**Comment by Shade-** [comment]
Hello, sorry I missed this. Please open a thread in MyBBoost so I can keep track of this. Thank you!
