### ISSUE TITLE
'fbbio' not such column

### ISSUE THREAD

**Issue by Swordancer** [Shade-/MyFacebook-Connect#67]
Im not sure if I did some mistake somewhere or it is bug, but in language file I don't see bio variable anymore and there is still 'fbbio', in  98 line of myfbconnect.php so when Im trying to register it uses update mysql command to update column that not exist after plugin install. There is no error if I remove this line.

**Comment by Shade-** [comment]
The issue has been fixed. Thank you for reporting. Will be included in 3.4, but you can refer to the commit and remove it on your own copy: 8628b30.
