### ISSUE TITLE
Bug report - exported log

### ISSUE THREAD

**Issue by Eldenroot** [Shade-/MyFacebook-Connect#69]
Here is the log from last version v3.4, maybe it can help you to debug
`<?xml version="1.0" encoding="ISO-8859-1"?>
<report version="3.4" name="MyFacebook Connect">
<id>26</id>
<dateline>1501437862</dateline>
<code>0</code>
<file>/home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/Helpers/FacebookRedirectLoginHelper.php</file>
<line>244</line>
<message>Cross-site request forgery validation failed. Required param "state" missing from persistent data.</message>
<trace>#0 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/Helpers/FacebookRedirectLoginHelper.php(221): Facebook\Helpers\FacebookRedirectLoginHelper->validateCsrf() #1 /home/users/carcassonne/carcassonneforum.cz/web/inc/plugins/MyFacebookConnect/class_facebook.php(127): Facebook\Helpers\FacebookRedirectLoginHelper->getAccessToken() #2 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect.php(63): MyFacebook->save_token() #3 {main}</trace>
</report>`

**Comment by Shade-** [comment]
Can you elaborate a bit more? Does this happen every now and then, or it prevents you from logging in/registering? Please give a detailed reproduction guide. Thank you.

**Comment by Eldenroot** [comment]
I can log in/register without any issue. I just get this error in MFC in ACP settingin logs.

**Comment by Shade-** [comment]
Reports are generated when users can't login. The report's dateline is 30/07/2017, which is fairly old. You can ignore it and delete it, as the issue has probably been fixed already.
