### ISSUE TITLE
Empty option - ACP

### ISSUE THREAD

**Issue by Eldenroot** [Shade-/MyFacebook-Connect#70]
https://community.mybb.com/thread-137797-post-1309861.html#pid1309861

**Comment by Shade-** [comment]
Check your language files; setting_myfbconnect_keep_running and setting_myfbconnect_keep_running_desc should be in inc/languages/[yourlanguage]/admin/myfbconnect.lang.php

You can also add the title and desc using the settings editing tool within the ACP. 
https://github.com/Shade-/MyFacebook-Connect/blob/master/inc/languages/english/admin/myfbconnect.lang.php#L21
https://github.com/Shade-/MyFacebook-Connect/blob/master/inc/languages/english/admin/myfbconnect.lang.php#L22

**Comment by Eldenroot** [comment]
The lang files are fine, but nothing is displayed.
