### ISSUE TITLE
August 1, 2018 - Facebook review app

### ISSUE THREAD

**Issue by Eldenroot** [Shade-/MyFacebook-Connect#71]
I get this message from Facebook every month, so it seems to be important. How can I solve this? Because it seems to be quite complex process when you wanna send your app to review.

![image](https://user-images.githubusercontent.com/778890/43093171-a0403864-8eaf-11e8-8883-6275a2522688.png)

**Comment by Shade-** [comment]
This doesn’t apply to MFC. Just ignore the warning.

**Comment by Eldenroot** [comment]
OK, thanks!
