### ISSUE TITLE
Weird bug - unlink FB account, link again and secondary primary usergroup is added

### ISSUE THREAD

**Issue by Eldenroot** [Shade-/MyFacebook-Connect#72]
Steps how to reproduce:
1) Link your existing forum account with your Facebook account (log in via Facebook button or set it in UCP)
2) If you have let say usergroup "B" which is granted after 100 posts and you link your account again your secondary usergroup is added to your account (usergroup "A") according to the in ACP in MFC plugin setting. 

I think that this is wrong behaviour, this should apply only to newly registered users, not to the existing accounts.

**Comment by Shade-** [comment]
MFC's destination usergroup applies to both new and existing users. New users get the usergroup as their primary, existing ones in their secondaries. Not sure what's wrong with that.

**Comment by Eldenroot** [comment]
I do not see any point to add secondary usergroup (for example "New registered user") for users with primary usergroup for example "Registered over 2 years".

At least you should add setting if it should apply as a secondary usergroup for already registered users.

**Comment by Shade-** [comment]
Alright, I see your point now. Might add an option for that.

**Comment by Eldenroot** [comment]
Thank you, it makes me angry, because I use secondary usergroups on my board and display them in postbit... so I have to manualy set them back...

**Comment by Shade-** [comment]
Fixed. Note that if you have already ran the upgrade script, you will need to apply the setting by yourself or downgrade to 3.3 and run the upgrade script when asked. To downgrade, you will need to edit mybb_datacache, search for shade_plugins row, and find MyFacebook Connect within the JSON string. You should see something like:

```a:XX:{s:18:"MyFacebook Connect";a:2:{s:5:"title";s:18:"MyFacebook Connect";s:7:"version";s:3:"3.4";}}```

Change the version to 3.3, then go to ACP > Tools and Maintenance > Cache manager > Rebuild cache for shade_plugins.

Replace the old files with the new ones, run the upgrade script.

**Comment by Eldenroot** [comment]
Isnt easier to release 3.4.1? ;)

Ok, I will do it, thank you

**Comment by Shade-** [comment]
You can also update the upgrade script's version from 3.4 to 3.4.1 [here](https://github.com/Shade-/MyFacebook-Connect/blob/master/inc/plugins/MyFacebookConnect/class_update.php#L208). I do not plan to add 3.4.1 so you'll be fine with the change.

**Comment by Shade-** [comment]
You will also need to update to 3.4.1 [here](https://github.com/Shade-/MyFacebook-Connect/blob/master/inc/plugins/myfbconnect.php#L51) in order to get the upgrade script notice.

**Comment by Shade-** [comment]
(note that the version you are testing is a pre-release, hence why 3.4.1 won't be released).

**Comment by Eldenroot** [comment]
Thank you!

**Comment by Shade-** [comment]
Does it work as expected? I'm aiming towards a release by this evening.

**Comment by Eldenroot** [comment]
Works fine, at least it seems to be. Thank you
