### ISSUE TITLE
Missing permissions #200

### ISSUE THREAD

**Issue by Eldenroot** [Shade-/MyFacebook-Connect#76]
![image](https://user-images.githubusercontent.com/778890/87871010-42796a80-c9ad-11ea-91c5-e6b6c92e148d.png)

I get this error when I wanna login via Facebook.

It was OK, I updated to MyBB 1.8.23 and after that NOK

@Shade-

**Comment by Eldenroot** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<report name="MyFacebook Connect" version="3.5">
		<id>116</id>
		<dateline>1595108159</dateline>
		<code>200</code>
		<file>/home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/Exceptions/FacebookResponseException.php</file>
		<line>137</line>
		<message>(#200) Missing Permissions</message>
		<trace>#0 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create()
#1 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct()
#4 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest()
#5 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/Facebook.php(336): Facebook\Facebook->sendRequest()
#6 /home/users/carcassonne/carcassonneforum.cz/web/inc/plugins/MyFacebookConnect/class_facebook.php(165): Facebook\Facebook->get()
#7 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect.php(66): MyFacebook->get_user()
#8 {main}</trace>
</report>`

**Comment by Shade-** [comment]
Thanks for reporting, I guess MyBB 1.8.23 introduces some critical changes. I will look at this ASAP.

**Comment by Eldenroot** [comment]
Hi, thank you in advance, because many users rely on the Facebook login :)

**Comment by Eldenroot** [comment]
Any clue? Thx!

**Comment by Shade-** [comment]
Please try the new version (504de94d7b72b75f22228201740a3941dd7a2c43) I've pushed. Facebook no longer accepts certain data points, so I have deleted the cover data point, and made location optional (it can be added to the scopes field). The verified field is also deprecated, so it has been dropped.

Please let me know how it goes since I use Flyover and not MFC on MyBBoost.

**Comment by Shade-** [comment]
To update, just replace the old files and run the upgrade script.

**Comment by Eldenroot** [comment]
@Shade- - hi, thank you, great support! I will try tomorrow and if anything I will let you know.

**Comment by Eldenroot** [comment]
OK, tested and works fine! Thx!
