### ISSUE TITLE
Cross site request

### ISSUE THREAD

**Issue by Eldenroot** [Shade-/MyFacebook-Connect#77]
![image](https://user-images.githubusercontent.com/778890/87871033-7f456180-c9ad-11ea-9794-2c6aa79b4842.png)

**Comment by Eldenroot** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<report name="MyFacebook Connect" version="3.5">
		<id>119</id>
		<dateline>1595148526</dateline>
		<code>0</code>
		<file>/home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/Helpers/FacebookRedirectLoginHelper.php</file>
		<line>244</line>
		<message>Cross-site request forgery validation failed. Required param "state" missing from persistent data.</message>
		<trace>#0 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect/src/Facebook/Helpers/FacebookRedirectLoginHelper.php(221): Facebook\Helpers\FacebookRedirectLoginHelper->validateCsrf()
#1 /home/users/carcassonne/carcassonneforum.cz/web/inc/plugins/MyFacebookConnect/class_facebook.php(128): Facebook\Helpers\FacebookRedirectLoginHelper->getAccessToken()
#2 /home/users/carcassonne/carcassonneforum.cz/web/myfbconnect.php(63): MyFacebook->save_token()
#3 {main}</trace>
</report>`

**Comment by Shade-** [comment]
This is possibly a temporary issue. Please reopen this if it's persistent.
